name: responsi_124230052
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
