name: responsi_124230052
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0                
  shared_preferences: ^2.2.2 
  url_launcher: ^6.2.1       
  hive_flutter: ^1.1.0         
  google_fonts: ^6.1.0         
  intl: ^0.19.0   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
